export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const PURCHESE_BURGER_START = 'PURCHESE_BURGER_START';
export const PURCHESE_BURGER_SUCCESS = 'PURCHESE_BURGER_SUCCESS';
export const PURCHESE_BURGER_FAIL = 'PURCHESE_BURGER_FAIL';
export const PURCHESE_INIT = 'PURCHESE_INIT';

export const FETCH_ORDERS_INIT = 'FETCH_ORDERS_INIT';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';